// REDUCER CONSTANT
module.exports = {
    LOGEDIN_USER: 'LOGEDIN_USER',
    RESET_STORE: 'RESET_STORE',
    USER_INFO: 'USER_INFO',
    USER_LOGEDOUT: 'USER_LOGEDOUT',
    SAVE_CHAT_LIST: 'SAVE_CHAT_LIST',
    SAVE_CHAT_ID_LIST: 'SAVE_CHAT_ID_LIST',
    SAVE_CHAT_USER_LIST: 'SAVE_CHAT_USER_LIST',
};
